### PR TITLE
Eslint-setup

### PR DESCRIPTION
**Pull request by lowe25**
eslint

### CODE REVIEW

**Comment by Tonyoooo13** [comment]
Grabe talaga yung mga github contributor! UwU

**Comment by pong0825** [comment]
Eyyy nice work

**Comment by BRETLORICA** [comment]
I find this UwU

**Comment by MiraneKazuya** [comment]
As expected from 2020 Github Archive Program Contributor, amazing work!

**Comment by Devjayz** [comment]
Wow thats a cool code

**Comment by Robert-Haru** [comment]
How to be you po?? Nice code btw

**Comment by orachtnyc** [comment]
Nice work!

**Review by orachtnyc — APPROVED** [review]

**Review by orachtnyc — COMMENTED** [review]
Well done!

**Review by MayeDay — COMMENTED** [review]
Good changes. Good work.

**Review by MayeDay — APPROVED** [review]
Good changes. Good work.

**Pull request merged**
